src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Controller/Home.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name = "HomePage")
     */
    public function showHomePage(): Response
    {


        return $this->render("Home/Home.html.twig");
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Category;


class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
               // get all categories !
               $AllCategory = $this->getDoctrine()
               ->getRepository(Category::class)
               ->findAll();
       
               dump($AllCategory);
       
        return $this->render('home/index.html.twig',[
            "categories" => $AllCategory
        ]);
    }


    /**
     * @Route("show/{id}", name="category")
     */
    public function showCategoryDetail(Request $request):Response
    {        
        $id  =  $request->attributes->get("id");

        // definit notre entité manager
        $em = $this->getDoctrine()->getManager();

        // add a category
        // $category = new Category();
        $category = $em->getRepository(Category::class)->find(1);

        $category->setImage("art_design-icon.png");

        $em->persist($category);
        $em->flush();

        return $this->renderForm("Category/index.html.twig",[
            "id" => $id,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Home page !{% endblock %}

{% block body %}


<div class="container">
  <h1 class="text_landing"> Find your <span class="text_title">dream </span> <br> jobs with us </h1>
  <img class="landingPagePhoto" src="/images/landingpage.png" alt="landing_page">
</div>

<div class="container_2">
  <h1 class="text_landing"> Browse <span class="text_title">Job Cateogry</span></h1>
  <section class="categories">

    {% for category in categories %}
    <a class="card card_cat" href="{{ path('category', { 'id': category.id}) }}">
      <div class="inner_container"</div>
          <img src="/images/icons/{{category.Image}}" class="card-img-top card_icon" alt="icon">
          <div class="card-body">
              <h3>{{category.name}}</h3>
              <p class="card-text">{{category.description}}</p>
          </div>
      </div>
  </a>
    {% endfor %}
  </section>
</div>

{% endblock %}

templates/home/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light container-fluid d-flex justify-content-evenly nav_bar">
    <a class="navbar-brand" href="/">
        <span class="text_title">Find</span> Your Job
    </a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu_bloc">
        <li class="nav-item">
            <a class="nav-link active" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="#">Category</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="#">Carreer advice</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="#">Post a job</a>
        </li>
    </ul>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 login_bloc">
        <li class="nav-item">
            <a class="nav-link active" href="#">Log In</a>
        </li>
        <button class="button_register">
            <a class="nav-link active" href="#">Register</a>
        </button>
    </ul>
</nav>